#!/bin/bash

# ProxyIP 1034 错误完整排查和修复脚本

echo "========================================="
echo "ProxyIP 1034 错误排查指南"
echo "========================================="
echo ""

echo "📋 问题描述："
echo "访问套了 Cloudflare CDN 的网站报错 1034"
echo "访问其他网站正常，说明 ProxyIP 未生效"
echo ""

echo "🔍 第一步：检查管理端配置保存"
echo "=========================================
"
echo "1. 登录管理后台"
echo "2. 进入【全局配置】→【反代IP管理】"
echo "3. 添加 ProxyIP（例如：ProxyIP.HK.CMLiussss.net:443）"
echo "4. 点击【保存配置】"
echo "5. 检查是否提示'✅ 配置已保存'"
echo ""

echo "🔍 第二步：验证数据库保存"
echo "========================================="
echo "访问管理端 Worker 的 /api/users 接口："
echo ""
echo "curl https://你的管理端域名/api/users | jq"
echo ""
echo "检查返回的 JSON："
echo "{"
echo "  \"users\": {...},"
echo "  \"settings\": {"
echo "    \"proxyIPs\": [\"ProxyIP.HK.CMLiussss.net:443\"],  ← 应该有值"
echo "    \"bestDomains\": [...]"
echo "  }"
echo "}"
echo ""

echo "❌ 如果 proxyIPs 是空数组，说明保存失败！"
echo ""

echo "🔍 第三步：检查节点端同步"
echo "========================================="
echo "访问节点 Worker 的 /debug 接口："
echo ""
echo "curl https://你的节点域名/debug | jq"
echo ""
echo "检查返回的 JSON："
echo "{"
echo "  \"users\": {...},"
echo "  \"settings\": {"
echo "    \"proxyIPs\": [\"ProxyIP.HK.CMLiussss.net:443\"],  ← 应该有值"
echo "    \"bestDomains\": [...]"
echo "  },"
echo "  \"lastUpdate\": \"2026-01-10T...\","
echo "  \"apiUrl\": \"https://...\""
echo "}"
echo ""

echo "❌ 如果 proxyIPs 是空数组，说明节点端同步失败！"
echo ""

echo "⚠️ 关键概念理解"
echo "========================================="
echo ""
echo "ProxyIP 在这个项目中的作用："
echo ""
echo "1. ProxyIP ≠ HTTP/SOCKS5 代理服务器"
echo "2. ProxyIP = Cloudflare 反代域名服务"
echo "3. 用途：提供'干净的'CDN 入口，避免被识别为 CF Worker IP"
echo ""
echo "为什么会报 1034 错误？"
echo ""
echo "客户端 → Worker (CF IP) → Cloudflare CDN 网站"
echo "                              ↓"
echo "                      检测到 CF IP → 返回 1034"
echo "                     （防止循环请求）"
echo ""
echo "ProxyIP 的正确使用方式："
echo ""
echo "客户端 → ProxyIP域名 → CF CDN → Worker → 目标网站"
echo "        (干净IP)     (SNI伪装)"
echo ""

echo "✅ 解决方案"
echo "========================================="
echo ""
echo "方案一：使用优选IP代替 ProxyIP（推荐）"
echo ""
echo "1. 在【全局配置】→【优选域名管理】中添加真实的优选IP："
echo "   146.56.130.12:443#电信优选"
echo "   104.18.0.1:443#HK节点"
echo ""
echo "2. 这些IP会出现在订阅中，客户端直接连接优选IP"
echo ""
echo "3. 流量路径："
echo "   客户端 → 优选IP(非CF) → CF CDN → Worker → 目标"
echo ""
echo "   优点：真正bypass CF检测，速度快"
echo ""

echo "方案二：修改订阅生成逻辑（复杂）"
echo ""
echo "需要修改代码，让节点使用 ProxyIP 作为连接地址"
echo "但由于 Worker 的出站限制，效果有限"
echo ""

echo "❌ 常见误区"
echo "========================================="
echo ""
echo "误区1：以为保存ProxyIP后，Worker会自动通过ProxyIP连接"
echo "事实：Worker的所有出站连接都来自CF IP池，无法改变"
echo ""
echo "误区2：以为ProxyIP是代理服务器"
echo "事实：ProxyIP是域名，用于订阅配置，不是代理"
echo ""
echo "误区3：删除后重新添加就能解决"
echo "事实：如果架构不对，添加多少次都没用"
echo ""

echo "🚀 立即修复步骤"
echo "========================================="
echo ""
echo "1. 【清空 ProxyIP】- 这个配置对当前架构无效"
echo ""
echo "2. 【添加真实优选IP到 bestDomains】："
echo "   进入【全局配置】→【优选域名管理】"
echo "   添加："
echo "   146.56.130.12:443#电信优选"
echo "   104.18.0.1:443#联通优选"
echo ""
echo "3. 【保存配置】"
echo ""
echo "4. 【更新订阅】"
echo "   在客户端（v2rayN/Clash等）中更新订阅"
echo ""
echo "5. 【选择优选IP节点访问】"
echo "   使用标注了'优选'的节点访问CF CDN网站"
echo ""

echo "📞 仍然无法解决？"
echo "========================================="
echo ""
echo "请提供以下信息："
echo ""
echo "1. 管理端 /api/users 返回的完整 JSON"
echo "2. 节点端 /debug 返回的完整 JSON"
echo "3. 客户端订阅链接获取的节点列表"
echo "4. 具体访问的网站域名"
echo "5. 客户端使用的是哪个节点"
echo ""

echo "========================================="
echo "排查完成！"
echo "========================================="
